### ISSUE TITLE
Vagrant provision failing on VirtualBox 5.1.6

### ISSUE THREAD

**Issue by robpml** [grtjn/mlvagrant#103]
details to follow, as 5.1.6 was the latest version, but this has now been updated to 5.1.8 - I have not tried this yet, but will update here when I do

Workaround - install Virtualbox 5.0.2 [https://www.virtualbox.org/wiki/Download_Old_Builds_5_0_pre18](url)

**Comment by grtjn** [comment]
The grtjn/centos-7.2 basebox, which is the most recent one, has vbox guest additions for version 5.0.12. It looks like running with vbox 5.1 is not compatible, causing mishap. It could be worth trying the bento/centos-7.2 basebox which has a slightly newer release which I haven't copied yet. Can't guarantee is has more recent guest additions though, and not sure they are downwards compatible..

**Comment by grtjn** [comment]
To be able to use a bento basebox, you'll have to edit the Vagrant file. It lists `grtjn/centos-` in two places. Replace both with `bento/centos-`, and retry creating the VM from scratch..

**Comment by grtjn** [comment]
I ran a test myself. Hit some other issue, but looks like the most recent bento basebox would work with VBox 5.1. I'll republish it under grtjn for mlvagrant asap..

**Comment by grtjn** [comment]
By the way, this seems related to #104..

**Comment by grtjn** [comment]
Latest baseboxes (6.8 / 7.2) that I published last night should fix this..
