### ISSUE TITLE
Automate install of GuestAdditions

### ISSUE THREAD

**Issue by robpml** [grtjn/mlvagrant#104]
How about automating the installation of the Vbox Guest Additions CD so we can share folders with the host (and use locally installed dev tools)

**Comment by grtjn** [comment]
The baseboxes do come with vbguest additions, but not the right ones..

**Comment by grtjn** [comment]
centos-7.1 has vbguest additions 5.0.2
centos-7.2 has vbguest additions 5.0.12
centos-7.2 v2.3.0 (which I am going to release) has vbguest additions 5.1.6 which likely work with VBox 5.1.x and below..

**Comment by grtjn** [comment]
Perhaps I should consider requiring vagrant-vbguest, and configure it to automatically install if there is a mismatch: https://github.com/dotless-de/vagrant-vbguest

**Comment by grtjn** [comment]
Or maybe not automatically (usually not necessary), but at least mention these convenient command-line commands to check and fix things if there is trouble:

https://github.com/dotless-de/vagrant-vbguest#running-as-a-command

**Comment by grtjn** [comment]
I published newer baseboxes, and will add docs about vagrant-vbguest in the README. Closing this ticket..

**Comment by grtjn** [comment]
New report:

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

**Comment by grtjn** [comment]
fixed with following steps..

Install kernel include headers (required by VBoxLinuxAdditions):

- sudo yum update && sudo yum -y install kernel-headers kernel-devel
- manually by downloading the iso file inside VM (e.g. wget) and installing it, e.g.
- wget http://download.virtualbox.org/virtualbox/5.1.14/VBoxGuestAdditions_5.1.14.iso -P /tmp
- sudo mount -o loop /tmp/VBoxGuestAdditions_5.1.14.iso /mnt
- sudo sh -x /mnt/VBoxLinuxAdditions.run # --keep

Double check that kernel extensions are up and running:

- sudo modprobe vboxsf
- sudo service VBoxService start

**Comment by grtjn** [comment]
The plugin vagrant-vbguest seems to default to updating available additions, which is only really necessary if VBox has a larger major or minor version. I'd prefer if vagrant-vbguest does not automatically mess things up, so I'd advice adding this to your Vagrantfile if it isn't in there yet:

```ruby
    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.no_install = true
    end
```

I'll add that by default to the Vagrantfile of mlvagrant

**Comment by grtjn** [comment]
The end conclusion is, it should not be necessary to install guestadditions automatically. Baseboxes 6.8 and 7.2 have pretty recent guestadditions that are compatible up to vbox 5.1.4 and a little beyond probably. A tool like vagrant-vbguest expects installers and compile tools to be available upfront, which is not the case, causing it to leave a worse state than without attempting guestadditions updates.

I'll freshen up baseboxes again with newer copies from the CHEF project if there are enough requests, and if those become available in the CHEF project.

I disable auto-install via #111. Closing this as wontfix..
