### ISSUE TITLE
Cannot use links for resource folders

### ISSUE THREAD

**Issue by kghmanuel** [grtjn/mlvagrant#113]
Given:

1. windows OS
2. D:\opt\vagrant is a link/junction to another folder, e.g. <JUNCTION>     vagrant [D:\Vanguard\code\mlvagrant\opt\vagrant]
3. D:\space\installers is a link/junction to another folder, e.g. <JUNCTION>     software [D:\installers]

* link/junction created using mklink /J command

Encountered the following error:

```
D:\VMs\democat>vagrant up --no-provision
==> democat-ml1: Mounting shared folders...
    democat-ml1: /vagrant => D:/VMs/democat
    democat-ml1: /opt/vagrant => D:/opt/vagrant
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attemped was:
 
set -e
mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` opt_vagrant /opt/vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` opt_vagrant /opt/vagrant
 
The error output from the command was:
 
/sbin/mount.vboxsf: mounting failed with the error: Invalid argument
```

**Comment by grtjn** [comment]
There are two issues going on here:
- Vagrant was unable to mount VirtualBox shared folders.
- Use of link/junction (created using mklink /J command)

The first is an issue with VBox itself. Upgrade to 5.2.14 seems to help.

The latter unfortunately simply doesn't seem to work with Vagrant/VBox.

**Comment by grtjn** [comment]
Got offline confirmation that 5.2.14 worked.
