### ISSUE TITLE
ml install requires sudo

### ISSUE THREAD

**Issue by Audarth** [grtjn/mlvagrant#119]
I updated vagrant and ml vagrant today and tried starting up a MarkLogic 9 machine but found that the MarkLogic installation step was failing.

My solution was to go to the "install-ml-centos.sh" script and change these lines to use sudo:

```
  # Run MarkLogic installer
  echo "Installing ML using /space/software/$installer ..."
  sudo rpm -i "/space/software/$installer"

  # Make sure MarkLogic is started
  sudo /sbin/service MarkLogic restart
```

Maybe an issue with the new box, or because of my Windows machine.

**Comment by grtjn** [comment]
ML install indeed requires sudo, but the entire script should be running with sudo. See https://github.com/grtjn/mlvagrant/blob/master/opt/vagrant/bootstrap-centos-master.sh
