### ISSUE TITLE
Attempting Install and Reinstall Throwing Lots of Errors (See log)

### ISSUE THREAD

**Issue by sjordan1975** [grtjn/mlvagrant#123]
Trying to get up and running with ML 9.0.4...

I getting lots of dependency failures, 404 errors and the like.

At the end of the install, it seems I do not have ML installed:

```
[vagrant@vagrant-ml9-ml1 ~]$ /sbin/service MarkLogic start
Redirecting to /bin/systemctl start  MarkLogic.service
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to manage system services or units.
Authenticating as: root
Password: 
==== AUTHENTICATION COMPLETE ===
Failed to start MarkLogic.service: Unit MarkLogic.service failed to load: No such file or directory.
```

See log attached.

[log.txt](https://github.com/grtjn/mlvagrant/files/1850082/log.txt)

**Comment by grtjn** [comment]
i haven't seen this issue with ML service before, but i suspect that is a side-effect of the failed package installs, which likely included packages required by the ML installer as well..

**Comment by grtjn** [comment]
The 404's might have been a temporary issue, with bad repo redirects. I'd have to try to see if I can reproduce..

**Comment by grtjn** [comment]
yum repo refs can get out of synch over time. It is suggesting itself to run `yum makecache fast`. I can add that to the scripts, but need to run some tests first..
