### ISSUE TITLE
Trying to install MarkLogicConverters-9.0-5.x86_64 fails - missing libs

### ISSUE THREAD

**Issue by sashamitrovich** [grtjn/mlvagrant#125]
This is a CentOS machine, doing an upgrade form ML 9.0-5

```
error: Failed dependencies:
	libgcc_s.so.1 is needed by MarkLogicConverters-9.0-5.x86_64
	libstdc++.so.6(GLIBCXX_3.4.15) is needed by MarkLogicConverters-9.0-5.x86_64
```

**Comment by grtjn** [comment]
I think a `yum install libgcc.i686 libstdc++.i686` should work, checking..

**Comment by grtjn** [comment]
It is `yum install libgcc libgcc.i686 libstdc++ libstdc++.i686` actually..

**Comment by grtjn** [comment]
This seems to work now..

**Comment by imrantech** [comment]
"yum install libgcc libgcc.i686 libstdc++ libstdc++.i686" worked for me too. Thanks.
