### ISSUE TITLE
Upgrade Vagrant wipes out /opt/vagrant directory

### ISSUE THREAD

**Issue by MJMoody** [grtjn/mlvagrant#126]
I just upgraded Vagrant on OSX to latest version - 2.1.1

After upgrading Vagrant, I also re-installed plugins, `vagrant-hostmanager` to 1.8.8, and `vagrant-vbguest` to 0.15.1.

I then tried creating a new ml-vagrant image -- but my /opt/vagrant scripts were all gone!

Looks like the /opt/vagrant directory was wiped clean and replaced with folders `bin` and `embedded` by the latest Vagrant installer.

**Comment by grtjn** [comment]
Thnx.. I'll consider moving over to /opt/mlvagrant instead.. I just need to think how to be backwards-compatible..

**Comment by grtjn** [comment]
I moved over to /opt/mlvagrant
