### ISSUE TITLE
Consider switching to private_network as default

### ISSUE THREAD

**Issue by grtjn** [grtjn/mlvagrant#24]
Works better for some people working in network with restrictions. May need to wait for release of Vagrant 1.7.3..

**Comment by grtjn** [comment]
Or find a way to make it configurable.

**Comment by grtjn** [comment]
You can switch to 'private_network', type: 'dhcp', but you may need to disable the dhcp that comes with VirtualBox. See here: https://github.com/mitchellh/vagrant/issues/3083

**Comment by mariannemyers** [comment]
Adding to this issue.

I ran into problems with the default public_network configuration whilst working on a "corporate" network.  Switching to private_network and disabling DHCP as @grtjn describes fixed my issues.

**Comment by grtjn** [comment]
I'll be moving forward on this in near future (read: as soon as I get round to it)..

**Comment by grtjn** [comment]
PR #42 fixes this for the master vm, but not yet for the slaves. Need to fix that, otherwise they will be out of synch..

**Comment by grtjn** [comment]
private dhcp default, private ip optional
