### ISSUE TITLE
http://download-i2.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm is not valid anymore

### ISSUE THREAD

**Issue by mstellwa** [grtjn/mlvagrant#43]
In install-node.sh there is a reference to http://download-i2.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm which will return a 404.

Correct url is http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

**Comment by grtjn** [comment]
Thnx!
