### ISSUE TITLE
Option to use internal network instead public for clusters

### ISSUE THREAD

**Issue by mstellwa** [grtjn/mlvagrant#45]
If the cluster should not be public available you could use internal network instead for public. 
The command for virtualbox is:
   master.vm.network "private_network", ip: "192.168.44.2",virtualbox__intnet: true
or with dhcp
  master.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

It would require an additional network adapter as well.

**Comment by grtjn** [comment]
See also #24..

**Comment by grtjn** [comment]
Closing this one..
