### ISSUE TITLE
Upgrade ruby (optionally)?

### ISSUE THREAD

**Issue by grtjn** [grtjn/mlvagrant#46]
Here some interesting notes on how to do that on centos. Unfortunately not an easy single yum install, but scriptable:

http://www.server-world.info/en/note?os=CentOS_6&p=ruby21

Here another link:

https://gist.github.com/mustafaturan/8290150

**Comment by grtjn** [comment]
First link works well, only need to replace 2.1.5 with 2.1.6..

**Comment by grtjn** [comment]
Note: centos 6 installs ruby 1.8.7, centos 7 installs ruby 2.0.0

**Comment by grtjn** [comment]
See also https://github.com/marklogic/roxy/issues/179

**Comment by grtjn** [comment]
Here a gist that uses rvm, looks relatively clean, but does likely need to compile.. https://gist.github.com/slouma2000/8619039

**Comment by grtjn** [comment]
Ran these today: https://www.rosehosting.com/blog/how-to-install-ruby-1-9-3-and-rubygems-1-8-24-on-centos-6-2/

..but with 1.9.3-p551 instead..

**Comment by robpml** [comment]
I had a few issues with the above methods, so followed the instructions here - [https://rvm.io/rvm/install](https://rvm.io/rvm/install)
Specifically stable version of RVM with ruby
`\curl -sSL https://get.rvm.io | bash -s stable --ruby`

**Comment by grtjn** [comment]
I don't think there is a high need for this anymore. Default CentOS version is now 7.2, which comes with Ruby v2.0.0 out of the box. Closing as won't fix..
