### ISSUE TITLE
yum write permissions

### ISSUE THREAD

**Issue by robpml** [grtjn/mlvagrant#55]
on running `vagrant provision` receive the following error:

==> pure-test-ml1: cp: cannot create directory `/space/software/yum': Protocol error
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by grtjn** [comment]
This will likely help:

`sudo chmod 775 /space/software`

Alternatively, you could chown it to $USER. This should be documented in the README..

**Comment by grtjn** [comment]
Documented in the README..
