### ISSUE TITLE
dependency warnings on provision - cluster not configured

### ISSUE THREAD

**Issue by robpml** [grtjn/mlvagrant#65]
when running `vagrant provision`

==> pure-test-ml1: /usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
==> pure-test-ml1: npm
==> pure-test-ml1:
==> pure-test-ml1: WARN unmet dependency /usr/lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
==> pure-test-ml1: npm
==> pure-test-ml1:  WARN
==> pure-test-ml1: unmet dependency undefined,
==> pure-test-ml1: npm WARN unmet dependency which is version undefined
==> pure-test-ml1: npm
==> pure-test-ml1:
==> pure-test-ml1: WARN unmet dependency /usr/lib/node_modules/fstream requires inherits@'~2.0.0' but will load
==> pure-test-ml1: npm
==> pure-test-ml1:  WARN
==> pure-test-ml1:
==> pure-test-ml1: unmet dependency
==> pure-test-ml1:  undefined,
==> pure-test-ml1: npm
==> pure-test-ml1: WARN
==> pure-test-ml1:
==> pure-test-ml1: unmet dependency
==> pure-test-ml1:  which is version undefined
==> pure-test-ml1: npm WARN unmet dependency
==> pure-test-ml1:  /usr/lib/node_modules/fstream-ignore requires inherits@'2' but will load
==> pure-test-ml1: npm
==> pure-test-ml1:
==> pure-test-ml1: WARN
==> pure-test-ml1:
==> pure-test-ml1: unmet dependency
==> pure-test-ml1:  undefined,
==> pure-test-ml1: npm
==> pure-test-ml1:
==> pure-test-ml1: WARN
==> pure-test-ml1:
==> pure-test-ml1: unmet dependency
==> pure-test-ml1:  which is version undefined
==> pure-test-ml1: npm WARN unmet dependency /usr/lib/node_modules/fstream-npm requires inherits@'2' but will load
==> pure-test-ml1: npm WARN
==> pure-test-ml1:  unmet dependency
==> pure-test-ml1:  undefined,
==> pure-test-ml1: npm
==> pure-test-ml1:  WARN
==> pure-test-ml1:
==> pure-test-ml1: unmet dependency
==> pure-test-ml1:  which is version undefined
==> pure-test-ml1: npm WARN unmet dependency /usr/lib/node_modules/glob requires inherits@'2' but will load
==> pure-test-ml1: npm WARN unmet dependency undefined,
==> pure-test-ml1: npm WARN unmet dependency which is version undefined
==> pure-test-ml1: npm
==> pure-test-ml1: WARN
==> pure-test-ml1: unmet dependency /usr/lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
==> pure-test-ml1: npm WARN
==> pure-test-ml1:  unmet dependency
==> pure-test-ml1:  undefined,
==> pure-test-ml1: npm
==> pure-test-ml1: WARN
==> pure-test-ml1:
==> pure-test-ml1: unmet dependency
==> pure-test-ml1:  which is version undefined
==> pure-test-ml1: npm WARN unmet dependency /usr/lib/node_modules/tar requires inherits@'2' but will load
==> pure-test-ml1: npm WARN unmet dependency undefined,
==> pure-test-ml1: npm
==> pure-test-ml1: WARN
==> pure-test-ml1: unmet dependency which is version undefined
==> pure-test-ml1: bower@1.5.2 /usr/lib/node_modules/bower

...

==> pure-test-ml2: Warning: Group development does not have any packages.
==> pure-test-ml2: No packages in any requested group available to install or update
==> pure-test-ml2: running /opt/vagrant/install-ml-centos.sh 8
==> pure-test-ml2: /opt/vagrant/install-ml-centos.sh: line 5: /tmp/8.project.properties: No such file or directory
==> pure-test-ml2: running /opt/vagrant/setup-ml-extra.sh -v 8 pure-test-ml1 pure-test-ml2 pure-test
==> pure-test-ml2: BOOTSTRAP_HOST is pure-test-ml1
==> pure-test-ml2: JOINING_HOST is pure-test-ml2
==> pure-test-ml2: VERSION is 8
==> pure-test-ml2: USER is admin
==> pure-test-ml2: LICENSEE is
==> pure-test-ml2: Adding host to cluster: pure-test-ml2...
==> pure-test-ml2: curl: (7) couldn't connect to host
==> pure-test-ml2: Retrieve pure-test-ml2 configuration...
==> pure-test-ml2: curl: (7) couldn't connect to host
==> pure-test-ml2: ERROR: Failed to fetch server config for pure-test-ml2
==> pure-test-ml2: Removing network suffix from hostname
==> pure-test-ml2: curl: (7) couldn't connect to host
==> pure-test-ml2: grep:
==> pure-test-ml2: hosts.html
==> pure-test-ml2: : No such file or directory
==> pure-test-ml2: grep: hosts.html
==> pure-test-ml2: : No such file or directory
==> pure-test-ml2: HOST_URL is
==> pure-test-ml2: HOST_ID is
==> pure-test-ml2: curl: (7) couldn't connect to host
==> pure-test-ml2: grep: host.html: No such file or directory
==> pure-test-ml2: HOST_XPATH is
==> pure-test-ml2: curl: (7) couldn't connect to host
==> pure-test-ml2: MarkLogic: unrecognized service
==> pure-test-ml2: Waiting for server restart..
==> pure-test-ml2: rm: cannot remove `*.html': No such file or directory
==> pure-test-ml2: ...pure-test-ml2 successfully added to the cluster.
==> pure-test-ml2: running /opt/vagrant/backup-yum-cache.sh

**Comment by grtjn** [comment]
You can ignore the NPM warnings.

About the other, things go wrong at ` /tmp/8.project.properties: No such file or directory`. That is actually caused by a bug in the bootstrap-centos-extra.sh script. Fixing that now..
