### ISSUE TITLE
Checking if box 'chef/centos-6.5' is up to date: 404 Not Found

### ISSUE THREAD

**Issue by grtjn** [grtjn/mlvagrant#68]
When starting an earlier created Vagrant vm, based on one of the chef/centos-* base boxes, the following is shown:

```
Bringing machine 'ml8-ml1' up with 'virtualbox' provider...
==> ml8-ml1: Checking if box 'chef/centos-6.5' is up to date...
==> ml8-ml1: There was a problem while downloading the metadata for your box
==> ml8-ml1: to check for updates. This is not an error, since it is usually due
==> ml8-ml1: to temporary network problems. This is just a warning. The problem
==> ml8-ml1: encountered was:
==> ml8-ml1: 
==> ml8-ml1: The requested URL returned error: 404 Not Found
==> ml8-ml1: 
==> ml8-ml1: If you want to check for box updates, verify your network connection
==> ml8-ml1: is valid and try again.
```

**Comment by grtjn** [comment]
The issue is caused by the removal of the chef base boxes from Atlas. See also #67.

It is best to take the latest Vagrantfile from this mlvagrant project, and create a new vm, that will be based on the same chef base boxes, but then republished under my own account on Atlas: https://atlas.hashicorp.com/grtjn.

One other alternative is to disable the `config.vm.box_check_update` setting. See also https://docs.vagrantup.com/v2/vagrantfile/machine_settings.html. Note that you need to put this setting in two places in the Vagrantfile: once for master, once for slave/data.

Last option, for the daring, is to change the metadata_url of the chef base boxes in your local Vagrant cache. To do so, locate the `.vagrant.d`, likely in your home directory. Inside you find directories like: `boxes/chef-VAGRANTSLASH-centos-6.5/1.0.0/`. In that folder you will find a file called `metadata_url`.It is a plain text file containing either:

```
https://vagrantcloud.com/chef/centos-6.5
```

Or:

```
https://atlas.hashicorp.com/chef/centos-6.5
```

Simply replace `chef` with `grtjn`, save the changes and you are done..

**Comment by chris-erickson** [comment]
@grtjn I'm out of ideas for how else to resolve this, but it seems your boxes don't support VMWare?  Is it possible to add this somehow?  We are dependents on the chef one, but alas, we use VMWare so yours don't work.  Thanks for any help you can provide.

**Comment by grtjn** [comment]
I'd be willing to add VMWare boxes, but I will have to replace the chef ones with bento. Those are supposed to be drop-in replacements, but might not be fully identical. Identical enough though I guess..

Let me have a look. I wrote these notes on how to recreate packages using Vagrant:

https://github.com/grtjn/centos-packer-templates#recovering-from-local-vagrant-cache

I'll start with grtjn/centos-6.5..

**Comment by grtjn** [comment]
Hmm, bento dropped the centos-6.5 boxes from atlas. @chris-erickson do you still have the vmware box in your local cache? If so you can still create new vm's with it if I am not mistaken, you should be able to just ignore not found messages..

**Comment by grtjn** [comment]
This may also be of interest, the older boxes are still all available, though I can't really test them myself at the moment, as I haven't installed VMWare yet:

https://github.com/chef/bento/blob/master/OLD-BOXES.md

**Comment by chris-erickson** [comment]
I have the old one, but it's not really viable for us to maintain these and distribute them to dev's one at a time.

The old boxes looks like it would work, but [a note in their README](https://github.com/chef/bento#build-notes) seems to indicate these won't work for us either (we're on Fusion).

I'm not entirely familiar with how this all works (adding boxes to Atlas, hosting them, etc), but I'll do my best to help out or test things with the right direction.

**Comment by grtjn** [comment]
Do you think you could init and package a box from your cache as i described in the other repo, and somehow share that big file with me? I'll attach it to my grtjn/centos-6.5 tag, so you can tell your devs to use that instead of chef/centos-6.5..

**Comment by grtjn** [comment]
Let me know if you are interested, as long as you can do the init, up, and package on your side, we surely can figure out how to get it uploaded to atlas under my name. Once there, you only need to change the urls in vagrant cache to replace chef with grtjn, and you are good. New devs can use grtjn/centos-6.5 from start..

**Comment by chris-erickson** [comment]
Working on doing this now, but stuck here:

```
> vagrant package --output chef-centos-6.5-x86_64-disk1.box
The "package" command is not supported with VMware. We recommend
taking a look at Packer (www.packer.io) as an option for creating
VMware images.
```
Can you point me in the right direction for VMWare?  I should be able to put this on Dropbox once complete.

**Comment by grtjn** [comment]
Googled a bit, and found these links:

https://gist.github.com/fightbulc/05de108f8ca6cc71e70c

https://www.vagrantup.com/docs/vmware/boxes.html

A little more effort than just vagrant package, but doable?

**Comment by grtjn** [comment]
The steps in the gist look pretty straight-forward..

**Comment by chris-erickson** [comment]
[Here's the box](https://dl.dropboxusercontent.com/u/753739/chef-centos6.5.box).  It made reference to packer internally, but I always pulled it as `chef/centos-6.5` so hopefully it's ok (perhaps that's just how it was built, not a packer distributed VM).



Let me know when you have it, so I can take it down.  Thanks!

**Comment by grtjn** [comment]
It is uploaded under grtjn/centos-6.5!

**Comment by grtjn** [comment]
If this works, I'd happily do it for other versions as well. Maybe a centos 7 version? Can't do it myself, I don't have VMWare Fusion nor Workstations, so Vagrant doesn't support the vmware provider on my machine..

**Comment by chris-erickson** [comment]
Thanks!  No need here for 7 right now, though.

**Comment by grtjn** [comment]
Closing again..
