### ISSUE TITLE
Filename of rpm files are "hardcoded" in install-ml-CentOS.sh

### ISSUE THREAD

**Issue by jojrg** [grtjn/mlvagrant#8]
The bootstrap script install-ml-CentOS.sh is looking for a list of rpm files to be installed depending on the marklogic version. The names of the rpm file are hardcoded. This means that the script needs to be adapted whenever a new minor MarkLogic release implies as new rpm file name. For example the rpm for ML8 EA2 is "MarkLogic-8.0-20141113.x86_64.rpm". The rpm for ML8 EA3 is MarkLogic-8.0-20141124.x86_64.rpm. 
It would be nice if the name of the rpm file could be configured through some property mechanism.

**Comment by grtjn** [comment]
Fix for #15 introduced a project.properties which could be used very well for this.

**Comment by grtjn** [comment]
This is fixed with #39..
