### ISSUE TITLE
Add comments on Proxying to README

### ISSUE THREAD

**Issue by grtjn** [grtjn/mlvagrant#82]
See http://justintung.com/2013/04/25/how-to-configure-proxy-settings-in-linux/ for some interesting suggestions..

**Comment by jongiddy** [comment]
I used the `vagrant-proxyconf` plugin and added this to the the Vagrantfile:
```
     mastername = get_vm_name(1)
 
+    hostnames = (1..@nr_hosts).map{|i| get_vm_name(i)}.join(",")
+    config.proxy.ftp      = "http://10.1.1.100:8080/"
+    config.proxy.http     = "http://10.1.1.100:8080/"
+    config.proxy.https    = "http://10.1.1.100:8080/"
+    config.proxy.no_proxy = "localhost,127.0.0.1,#{hostnames}"
+  
     config.hostmanager.enabled = false
     config.hostmanager.manage_host = true
     config.hostmanager.include_offline = true
```

Would it be worth adding this code inside a guard expression and having the proxy as an optional setting in `project.properties`?

**Comment by grtjn** [comment]
Looks great! PR's always welcome.. :)
