### ISSUE TITLE
File download aborts, vagrant up cannot continue

### ISSUE THREAD

**Issue by mariannemyers** [grtjn/mlvagrant#84]
I encountered the following error while trying to setup a new VM:

```
    dib-ml1: Downloading: https://atlas.hashicorp.com/grtjn/boxes/centos-6.7/versions/2.2.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

transfer closed with 31511811 bytes remaining to read
```

Retrying `vagrant up --no-provision`

```
    dib-ml1: Downloading: https://atlas.hashicorp.com/grtjn/boxes/centos-6.7/versions/2.2.0/providers/virtualbox.box
==> dib-ml1: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

HTTP server doesn't seem to support byte ranges. Cannot resume.
```

The download of the above virtualbox.box file somehow terminated.

I was able to resolve this error, but removing the following file:
`~/.vagrant.d/tmp/boxaec5ab74a7694fd5e752da440626f8a69973800c`

After deleting the above file, running `vagrant up --no-provision` again was able to complete successfully.  The hash for this download is likely different per each system, but should have a timestamp of close to when the vagrant up failed.

We should add this to a troubleshooting guide.

**Comment by grtjn** [comment]
Vagrant might also provide a nicer command to flush temp files, would have to search on internet..

**Comment by grtjn** [comment]
It might have been very straight-forward actually. There is a `vagrant box` command with options like `update` and `remove`. I should add a section for that in the README..
