### ISSUE TITLE
Check out Vagrant 1.8 and Otto project

### ISSUE THREAD

**Issue by grtjn** [grtjn/mlvagrant#86]
https://www.hashicorp.com/blog/vagrant-1-8.html
https://ottoproject.io/

**Comment by peetkes** [comment]
Hi Geert,
Vagrant 1.8 will install in /opt/vagrant as opposed to /Application/vagrant for the previous versions.
So if you chmod the /opt/vagrant folder you will always get this error:
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /opt/vagrant in PATH, mode 040777
Does vagrant user need write permissions in /opt/vagrant? 
Maybe 'sudo cp mlvagrant/opt/vagrant /opt/vagrant' would be sufficient.

**Comment by grtjn** [comment]
It doesn't need write acces, but it does need read and exec access, so 755 should be enough, if it isn't at that level yet..

**Comment by grtjn** [comment]
/space/software probably does need to be 777, that is where the mlvagrant scripts put the yum cache for reuse..

**Comment by grtjn** [comment]
Otto project has been decommissioned by the way: https://www.ottoproject.io/

And Vagrant is currently at 1.8.7. Apart from the chmod on /opt/vagrant/ I haven't heard issues so far, so I'm assuming Vagrant 1.8 works just fine. In fact, I think I'm going to upgrade, as it seems to do some smart cloning of vm's to save disk space!

**Comment by grtjn** [comment]
I guess it is now down to a README update then..

**Comment by grtjn** [comment]
Funny, I have been running with 755 for /opt/vagrant for ages, apparently..
