### ISSUE TITLE
Add support for ML9

### ISSUE THREAD

**Issue by grtjn** [grtjn/mlvagrant#91]

**Comment by vladistan** [comment]
Is it even available?

**Comment by grtjn** [comment]
The early-access program has been opened, you can sign up if you are interested:

https://ea.marklogic.com

**Comment by vladistan** [comment]
That form asks for Marklogic contact ID.   What should I put in there?

**Comment by grtjn** [comment]
Preferably the email of a MarkLogic Account Executive or Sales Engineer, but you can put in mine as well. It starts with Geert.Josten..

**Comment by grtjn** [comment]
And then cross fingers.. :-P

**Comment by grtjn** [comment]
Note: mlvagrant seems to run fine with MarkLogic 9 EA installer, but slush-marklogic-node and roxy fail because of an API change..
