### ISSUE TITLE
Question re: license application

### ISSUE THREAD

**Issue by mflatscher** [grtjn/mlvagrant#93]
Is automatic application of licenses expected to work for all hosts in a cluster, or just the bootstrap host? With a key in /opt/vagrant/ml_8_license.properties and proper version configured in /opt/vagrant/setup-ml-master.sh and /opt/vagrant/setup-ml-extra.sh, my license only gets applied on the first host. Is there a known gotcha?

**Comment by grtjn** [comment]
Known issue, but hesitant to fix. In a production situation you are supposed to install different licenses on each node..

**Comment by mflatscher** [comment]
Found the pertinent code. Agree with your social/business concern. Closing this.
