### ISSUE TITLE
Setting static IP Address in clustered configuration

### ISSUE THREAD

**Issue by ChrisDay-Australia** [grtjn/mlvagrant#99]
Had to edit the Vagrantfile in order to get static IP addressing working with a cluster configuration.

Original Vagrantfile code:
```ruby
    def inc_ip(ip, i)
      newip = "#{ip}"
      nr = "#{ip}"
      nr.gsub!(/^(.*\.)+/, "").to_i
      newip.gsub!(/\.\d+$/, ".#{nr + i}")
      newip
    end
```

Edited Vagrantfile code:

 newip.gsub!(/\.\d+$/, ".#{**nr.to_i** + i}")

```ruby
    def inc_ip(ip, i)
      newip = "#{ip}"
      nr = "#{ip}"
      nr.gsub!(/^(.*\.)+/, "").to_i
      newip.gsub!(/\.\d+$/, ".#{nr.to_i + i}")
      newip
    end
```

Once edit in place, each node gets a static IP address based on the settings in the project.properties file.

**Comment by grtjn** [comment]
Looks like a very logical patch, thnx for reporting!
